//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informations
    {
        public int Id { get; set; }
        public string description { get; set; }
    
        public virtual Tags tag_id { get; set; }
        public virtual Picture picture_id { get; set; }
    }
}
