//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContractAttribute(Name="Informations", Namespace="http://schemas.datacontract.org/2004/07/WindowsFormsApp1", IsReference=true)]
    public partial class Informations : object, IExtensibleDataObject
    {
        
        private ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private string descriptionField;
        
        private WindowsFormsApp1.Picture picture_idField;
        
        private WindowsFormsApp1.Tags tag_idField;
        
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [DataMemberAttribute()]
        public WindowsFormsApp1.Picture picture_id
        {
            get
            {
                return this.picture_idField;
            }
            set
            {
                this.picture_idField = value;
            }
        }
        
        [DataMemberAttribute()]
        public WindowsFormsApp1.Tags tag_id
        {
            get
            {
                return this.tag_idField;
            }
            set
            {
                this.tag_idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContractAttribute(Name="Picture", Namespace="http://schemas.datacontract.org/2004/07/WindowsFormsApp1", IsReference=true)]
    public partial class Picture : object, IExtensibleDataObject
    {
        
        private ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private System.DateTime created_atField;
        
        private bool deletedField;
        
        private string full_nameField;
        
        private string pathField;
        
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [DataMemberAttribute()]
        public System.DateTime created_at
        {
            get
            {
                return this.created_atField;
            }
            set
            {
                this.created_atField = value;
            }
        }
        
        [DataMemberAttribute()]
        public bool deleted
        {
            get
            {
                return this.deletedField;
            }
            set
            {
                this.deletedField = value;
            }
        }
        
        [DataMemberAttribute()]
        public string full_name
        {
            get
            {
                return this.full_nameField;
            }
            set
            {
                this.full_nameField = value;
            }
        }
        
        [DataMemberAttribute()]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContractAttribute(Name="Tags", Namespace="http://schemas.datacontract.org/2004/07/WindowsFormsApp1", IsReference=true)]
    public partial class Tags : object, IExtensibleDataObject
    {
        
        private ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private string nameField;
        
        public ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="InterfacePictureTagsInformations")]
public interface InterfacePictureTagsInformations
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceInformations/saveInformations", ReplyAction="http://tempuri.org/InterfaceInformations/saveInformationsResponse")]
    WindowsFormsApp1.Informations saveInformations(string path, string tag, string value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceInformations/saveInformations", ReplyAction="http://tempuri.org/InterfaceInformations/saveInformationsResponse")]
    System.Threading.Tasks.Task<WindowsFormsApp1.Informations> saveInformationsAsync(string path, string tag, string value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceInformations/displaySearchResults", ReplyAction="http://tempuri.org/InterfaceInformations/displaySearchResultsResponse")]
    string[] displaySearchResults(string description, string tag);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceInformations/displaySearchResults", ReplyAction="http://tempuri.org/InterfaceInformations/displaySearchResultsResponse")]
    System.Threading.Tasks.Task<string[]> displaySearchResultsAsync(string description, string tag);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePicture/createPicture", ReplyAction="http://tempuri.org/InterfacePicture/createPictureResponse")]
    WindowsFormsApp1.Picture createPicture(string path);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePicture/createPicture", ReplyAction="http://tempuri.org/InterfacePicture/createPictureResponse")]
    System.Threading.Tasks.Task<WindowsFormsApp1.Picture> createPictureAsync(string path);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePicture/deletePicture", ReplyAction="http://tempuri.org/InterfacePicture/deletePictureResponse")]
    void deletePicture(string path);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePicture/deletePicture", ReplyAction="http://tempuri.org/InterfacePicture/deletePictureResponse")]
    System.Threading.Tasks.Task deletePictureAsync(string path);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceTags/createTags", ReplyAction="http://tempuri.org/InterfaceTags/createTagsResponse")]
    WindowsFormsApp1.Tags createTags(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceTags/createTags", ReplyAction="http://tempuri.org/InterfaceTags/createTagsResponse")]
    System.Threading.Tasks.Task<WindowsFormsApp1.Tags> createTagsAsync(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceTags/getTags", ReplyAction="http://tempuri.org/InterfaceTags/getTagsResponse")]
    string[] getTags();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceTags/getTags", ReplyAction="http://tempuri.org/InterfaceTags/getTagsResponse")]
    System.Threading.Tasks.Task<string[]> getTagsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceTags/saveTag", ReplyAction="http://tempuri.org/InterfaceTags/saveTagResponse")]
    WindowsFormsApp1.Tags saveTag(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceTags/saveTag", ReplyAction="http://tempuri.org/InterfaceTags/saveTagResponse")]
    System.Threading.Tasks.Task<WindowsFormsApp1.Tags> saveTagAsync(string name);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface InterfacePictureTagsInformationsChannel : InterfacePictureTagsInformations, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class InterfacePictureTagsInformationsClient : System.ServiceModel.ClientBase<InterfacePictureTagsInformations>, InterfacePictureTagsInformations
{
    
    public InterfacePictureTagsInformationsClient()
    {
    }
    
    public InterfacePictureTagsInformationsClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public InterfacePictureTagsInformationsClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public InterfacePictureTagsInformationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public InterfacePictureTagsInformationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public WindowsFormsApp1.Informations saveInformations(string path, string tag, string value)
    {
        return base.Channel.saveInformations(path, tag, value);
    }
    
    public System.Threading.Tasks.Task<WindowsFormsApp1.Informations> saveInformationsAsync(string path, string tag, string value)
    {
        return base.Channel.saveInformationsAsync(path, tag, value);
    }
    
    public string[] displaySearchResults(string description, string tag)
    {
        return base.Channel.displaySearchResults(description, tag);
    }
    
    public System.Threading.Tasks.Task<string[]> displaySearchResultsAsync(string description, string tag)
    {
        return base.Channel.displaySearchResultsAsync(description, tag);
    }
    
    public WindowsFormsApp1.Picture createPicture(string path)
    {
        return base.Channel.createPicture(path);
    }
    
    public System.Threading.Tasks.Task<WindowsFormsApp1.Picture> createPictureAsync(string path)
    {
        return base.Channel.createPictureAsync(path);
    }
    
    public void deletePicture(string path)
    {
        base.Channel.deletePicture(path);
    }
    
    public System.Threading.Tasks.Task deletePictureAsync(string path)
    {
        return base.Channel.deletePictureAsync(path);
    }
    
    public WindowsFormsApp1.Tags createTags(string name)
    {
        return base.Channel.createTags(name);
    }
    
    public System.Threading.Tasks.Task<WindowsFormsApp1.Tags> createTagsAsync(string name)
    {
        return base.Channel.createTagsAsync(name);
    }
    
    public string[] getTags()
    {
        return base.Channel.getTags();
    }
    
    public System.Threading.Tasks.Task<string[]> getTagsAsync()
    {
        return base.Channel.getTagsAsync();
    }
    
    public WindowsFormsApp1.Tags saveTag(string name)
    {
        return base.Channel.saveTag(name);
    }
    
    public System.Threading.Tasks.Task<WindowsFormsApp1.Tags> saveTagAsync(string name)
    {
        return base.Channel.saveTagAsync(name);
    }
}
