//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/InformationsTagsPictures")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Informations", Namespace="http://schemas.datacontract.org/2004/07/InformationsTagsPictures", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Informations : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp2.ServiceReference1.Picture picture_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp2.ServiceReference1.Tags tag_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormsApp2.ServiceReference1.Picture picture_id {
            get {
                return this.picture_idField;
            }
            set {
                if ((object.ReferenceEquals(this.picture_idField, value) != true)) {
                    this.picture_idField = value;
                    this.RaisePropertyChanged("picture_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormsApp2.ServiceReference1.Tags tag_id {
            get {
                return this.tag_idField;
            }
            set {
                if ((object.ReferenceEquals(this.tag_idField, value) != true)) {
                    this.tag_idField = value;
                    this.RaisePropertyChanged("tag_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Picture", Namespace="http://schemas.datacontract.org/2004/07/InformationsTagsPictures", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Picture : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime created_atField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool deletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string full_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime created_at {
            get {
                return this.created_atField;
            }
            set {
                if ((this.created_atField.Equals(value) != true)) {
                    this.created_atField = value;
                    this.RaisePropertyChanged("created_at");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool deleted {
            get {
                return this.deletedField;
            }
            set {
                if ((this.deletedField.Equals(value) != true)) {
                    this.deletedField = value;
                    this.RaisePropertyChanged("deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string full_name {
            get {
                return this.full_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.full_nameField, value) != true)) {
                    this.full_nameField = value;
                    this.RaisePropertyChanged("full_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string path {
            get {
                return this.pathField;
            }
            set {
                if ((object.ReferenceEquals(this.pathField, value) != true)) {
                    this.pathField = value;
                    this.RaisePropertyChanged("path");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tags", Namespace="http://schemas.datacontract.org/2004/07/InformationsTagsPictures", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Tags : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        WindowsFormsApp2.ServiceReference1.CompositeType GetDataUsingDataContract(WindowsFormsApp2.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(WindowsFormsApp2.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/saveInformations", ReplyAction="http://tempuri.org/IService1/saveInformationsResponse")]
        WindowsFormsApp2.ServiceReference1.Informations saveInformations(string path, string tag, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/saveInformations", ReplyAction="http://tempuri.org/IService1/saveInformationsResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.Informations> saveInformationsAsync(string path, string tag, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/displaySearchResults", ReplyAction="http://tempuri.org/IService1/displaySearchResultsResponse")]
        string[] displaySearchResults(string description, string tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/displaySearchResults", ReplyAction="http://tempuri.org/IService1/displaySearchResultsResponse")]
        System.Threading.Tasks.Task<string[]> displaySearchResultsAsync(string description, string tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/createPicture", ReplyAction="http://tempuri.org/IService1/createPictureResponse")]
        WindowsFormsApp2.ServiceReference1.Picture createPicture(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/createPicture", ReplyAction="http://tempuri.org/IService1/createPictureResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.Picture> createPictureAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletePicture", ReplyAction="http://tempuri.org/IService1/deletePictureResponse")]
        void deletePicture(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deletePicture", ReplyAction="http://tempuri.org/IService1/deletePictureResponse")]
        System.Threading.Tasks.Task deletePictureAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/createTags", ReplyAction="http://tempuri.org/IService1/createTagsResponse")]
        WindowsFormsApp2.ServiceReference1.Tags createTags(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/createTags", ReplyAction="http://tempuri.org/IService1/createTagsResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.Tags> createTagsAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTags", ReplyAction="http://tempuri.org/IService1/getTagsResponse")]
        string[] getTags();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTags", ReplyAction="http://tempuri.org/IService1/getTagsResponse")]
        System.Threading.Tasks.Task<string[]> getTagsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/saveTag", ReplyAction="http://tempuri.org/IService1/saveTagResponse")]
        WindowsFormsApp2.ServiceReference1.Tags saveTag(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/saveTag", ReplyAction="http://tempuri.org/IService1/saveTagResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.Tags> saveTagAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsApp2.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsApp2.ServiceReference1.IService1>, WindowsFormsApp2.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WindowsFormsApp2.ServiceReference1.CompositeType GetDataUsingDataContract(WindowsFormsApp2.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(WindowsFormsApp2.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public WindowsFormsApp2.ServiceReference1.Informations saveInformations(string path, string tag, string value) {
            return base.Channel.saveInformations(path, tag, value);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.Informations> saveInformationsAsync(string path, string tag, string value) {
            return base.Channel.saveInformationsAsync(path, tag, value);
        }
        
        public string[] displaySearchResults(string description, string tag) {
            return base.Channel.displaySearchResults(description, tag);
        }
        
        public System.Threading.Tasks.Task<string[]> displaySearchResultsAsync(string description, string tag) {
            return base.Channel.displaySearchResultsAsync(description, tag);
        }
        
        public WindowsFormsApp2.ServiceReference1.Picture createPicture(string path) {
            return base.Channel.createPicture(path);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.Picture> createPictureAsync(string path) {
            return base.Channel.createPictureAsync(path);
        }
        
        public void deletePicture(string path) {
            base.Channel.deletePicture(path);
        }
        
        public System.Threading.Tasks.Task deletePictureAsync(string path) {
            return base.Channel.deletePictureAsync(path);
        }
        
        public WindowsFormsApp2.ServiceReference1.Tags createTags(string name) {
            return base.Channel.createTags(name);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.Tags> createTagsAsync(string name) {
            return base.Channel.createTagsAsync(name);
        }
        
        public string[] getTags() {
            return base.Channel.getTags();
        }
        
        public System.Threading.Tasks.Task<string[]> getTagsAsync() {
            return base.Channel.getTagsAsync();
        }
        
        public WindowsFormsApp2.ServiceReference1.Tags saveTag(string name) {
            return base.Channel.saveTag(name);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.ServiceReference1.Tags> saveTagAsync(string name) {
            return base.Channel.saveTagAsync(name);
        }
    }
}
